### ISSUE TITLE
Checking if NaN exists, returning true

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#25]
Hi all,
I came across with this sample (6acf3abf8e68d97b02f0b3502b1ca58c)
https://malwr.com/analysis/NjhmZGQ4YzU5ZmViNDhhNzljMmI3ODZjN2YwNTY0NWQ/
Executing it in a sandbox I got some outputs like: URLs,  download a PE file and so on 
when I use run.js i get this output 
Analyzing ../sample/js/32264.js
The file seems to be encoded with ascii.
Rewriting code...
Rewritten successfully.
Reading registry key HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\EXPLORER\SHELL FOLDERS\COMMON DOCUMENTS
Unknown registry key!
Checking if  exists, returning true
Checking if NaN exists, returning true
Checking if  exists, returning true
Checking if NaN exists, returning true
Checking if  exists, returning true
Checking if NaN exists, returning true
Checking if  exists, returning true
Checking if NaN exists, returning true
Checking if  exists, returning true
Checking if NaN exists, returning true
..... .... ....
Rewriting code...
    Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
    Rewriting typeof calls (use --no-typeof-rewrite to skip)...
    Rewriting eval calls (use --no-eval-rewrite to skip)...
    Rewriting try/catch statements (use --no-catch-rewrite to skip)...
Rewritten successfully.
@CapacitorSet do you have any idea?
best regards
PS: I'm using the V.1.8.0

**Comment by CapacitorSet** [comment]
Thanks for the report.

This is the type of sample that requires manual analysis in addition to the emulation features provided box-js. If you deobfuscate it a bit by:

 * unwrapping the `eval` call (it's the second item in `snippets.json`, beginning with `QChbfFwvXpjYaMxJdWK = new ActiveXObject("SheLL.aPPlIcAtiON");`) and replace it with the actual source code
 * and replace the simple functions appearing in the new source code (`jyYmeKuNIrDQRodLUni` with `String.fromCharCode`, `aKoSOZefyMAtkTlPL` with `RLUwOxGybIaheXJ.FolderExists`, `YqJIOCUTvwpnRjgEa(a, b)` with `a.charCodeAt(b)`

You'll see that [the resulting source code](https://gist.github.com/CapacitorSet/699cd66ea8da7744461334f402212b93) contains a line like this:

```js
foo != bar && 1 == foo.FolderExists(bar) && 0 == foo.FolderExists(baz)
```

It is equivalent to this:

```js
if (foo != bar)
    if (foo.FolderExists(bar) == true)
        if (foo.FolderExists(baz) == true)
            /* Do something */
```

Of course, box-js doesn't know which folders actually exist and which don't (doing so would require access to the list of files in a standard Windows install, which I may add sometime), so you can either tell it to always answer `ŧrue` to `.FolderExists` (default behaviour) or `false` (with the `--no-file-exists` flag), there is no inbetween.

Once we fix that, the script still fails, trying to execute a long string of `\u0000` (NUL characters). This happens most likely because box-js can't find a value for `HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\EXPLORER\SHELL FOLDERS\COMMON DOCUMENTS`. I added that in  5429579, and now it works correctly, even downloading a payload.

Hashes: 922048441804e3de60ccfe19c1a91f4b (md5), 52e4fced329f609f2977696d427560da0d67480c8b286dd4ccb3ae927674471e (sha256)

**Comment by CapacitorSet** [comment]
I'll add an option to prompt the user when FileExists, as well as a list of files and registry keys from a default Windows install, so I'm not closing this issue for now.

**Comment by CapacitorSet** [comment]
The list of registry keys was added in e21fb2a97534aa7057b03cf3ac906eb4278f631c - finally!

I don't think I'll add a list of files, it seems excessive for now.
