### ISSUE TITLE
Unable to decode JS

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#30]
[img.txt](https://github.com/CapacitorSet/box-js/files/1197934/img.txt)
I guess this is very obfuscated JS and even uglify raises some errors:
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
[info] Rewriting code...
[info]     Preprocessing with uglify-js v3.0.24 (remove --preprocess to skip)...
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[info]     Rewriting typeof calls (use --no-typeof-rewrite to skip)...
[info]     Rewriting eval calls (use --no-eval-rewrite to skip)...
[info]     Rewriting try/catch statements (use --no-catch-rewrite to skip)...
[info] Rewritten successfully.
[info] Rewriting code...
[info]     Preprocessing with uglify-js v3.0.24 (remove --preprocess to skip)...
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[info]     Rewriting typeof calls (use --no-typeof-rewrite to skip)...
[info]     Rewriting eval calls (use --no-eval-rewrite to skip)...
[info]     Rewriting try/catch statements (use --no-catch-rewrite to skip)...
[info] Rewritten successfully.
[info] Rewriting code...
[info]     Preprocessing with uglify-js v3.0.24 (remove --preprocess to skip)...
[error] Couldn't preprocess with uglify-js: {"message":"'return' outside of function","filename":"0","line":4,"col":4,"pos":337}
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[error] Error: Line 4: Illegal return statement
[error] 
[error] This doesn't seem to be a JavaScript/WScript file.
If this is a JSE file (JScript.Encode), compile
decoder.c and run it on the file, like this:

cc decoder.c -o decoder
./decoder ../sample/js/img.js ../sample/js/img.js.

**Comment by Nwinternights** [comment]
@CapacitorSet do you have any ideas?
Of course If I submit that sample on a sandbox I can extract URLS, payload ecc ecc.

**Comment by CapacitorSet** [comment]
I saw the issue yesterday, but haven't had much time to investigate it. As always, I'll report back when I fixed the bug or have updates.

**Comment by CapacitorSet** [comment]
I think I got this.

This happens because box-js has [a patch](https://github.com/CapacitorSet/box-js/blob/master/patch.js#L19) that allows it to rewrite the body of `Function`s. However, if the body has `return` in it, uglify-js will complain because to it, it seems to be outside of a function.

That specific error can be fixed by adding a flag to uglify-es to make it work with `return`s outside of functions, but then you will find that Esprima will complain [when parsing in `analyze.js`](https://github.com/CapacitorSet/box-js/blob/master/analyze.js#L132). Esprima doesn't have a flag for allowing `return` outside of functions, so I'll have to use Acorn instead.

**Comment by CapacitorSet** [comment]
By the way, in the meanwhile you can use `--no-rewrite` to make it work.
