### ISSUE TITLE
Automatically upload .exe samples on Virustotal

### ISSUE THREAD

**Issue by fnzv** [CapacitorSet/box-js#34]
Hi,
Could be a good idea to automatically upload samples on Virustotal via public API after the dropper downloaded the .exe file? (or Malwr, but i don't see APIs so will be more tricky)

Un tizio dall'ESC2k17

**Comment by CapacitorSet** [comment]
Ciao, grazie dell'interesse :)

I had already looked into integration with VirusTotal, but unfortunately I found it problematic:
 * Their public API is [limited to 4 requests per minute](https://www.virustotal.com/en/documentation/public-api/), which is not enough for one person analyzing a handful of samples, let alone the entire user base of box-js.
 * The documentation says that you can get a private API key if "if you run [...] any other automation that is going to provide resources to VirusTotal and not only retrieve reports". I contacted them, and they offered services starting at 600 €/month. At this time there's no way I can afford that, so direct integration is out of discussion.

If you know someone at VirusTotal who can provide me with an API key for free or very cheap, I would be glad to add direct VT integration (i.e. with an API key for box-js); otherwise, I can still implement integration with a user-provided API key, but I think it wouldn't be as useful, so it would be a low-priority feature.

Integration with Malwr is on the to-do list, on the other hand, as mentioned in issue #33. I'll write them an e-mail and see if I can get some kind of public API; either way, the submission form can be easily automated.

**Comment by fnzv** [comment]
Ah okk, makes sense that they ratelimit requests.
I look forward for the cuckoo/Malwr integration 

Great project and keep it up 👍

**Comment by CapacitorSet** [comment]
Fixed, see the [docs](https://github.com/CapacitorSet/box-js/tree/master/integrations#cuckoo-malwr-virustotal).

Example usage:

```
# box-js ~/samples --download
box-export ~/samples --vt-key=123abc --vt-executables --vt-urls
```

The command above will scan the `samples` folder for results, and submit all executable files and URLs to VirusTotal.
